let selected='Criar Prompt Profissional', voiceGender='female';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function show(id){const e=$(id);e.classList.remove('hidden');e.scrollIntoView({behavior:'smooth',block:'start'})}
function hide(id){$(id).classList.add('hidden')}
$('#guideBtn').onclick=()=>show('#guide');$('#fastBtn').onclick=()=>show('#workspace');$('#helpBtn').onclick=()=>show('#help');
$$('[data-close]').forEach(b=>b.onclick=()=>hide('#'+b.dataset.close));
const flows={
creator:{title:'🎬 Criadores & Redes',text:'Vamos fazer juntos: escolha a rede, diga o tema e formato. O ChatCreova prepara roteiro, cenas, narração, CTA e publicação.',action:'Abrir Criadores & Redes',target:'#workspace'},
sales:{title:'🛒 Vendas & E-commerce',text:'Comece pelo produto. Preserve o produto original. Depois montamos gancho, anúncio, roteiro UGC, cenas, CTA, título, descrição e hashtags.',action:'Abrir fluxo de vendas',target:'#workspace'},
education:{title:'🎓 Educação & Acadêmico',text:'Escolha Aluno, Professor ou Universitário. Prepare explicação, estudo, atividade, aula, apresentação ou estrutura acadêmica.',action:'Abrir Educação',target:'#workspace'},
voice:{title:'🎙️ Estúdio de Voz V4',text:'Cole até 7.000 caracteres, escolha voz feminina ou masculina e ouça usando as vozes disponíveis no aparelho.',action:'Abrir Estúdio de Voz',target:'#voiceStudio'},
cuts:{title:'✂️ Cortes Inteligentes',text:'Defina assunto e duração. A V4 cria um plano local de cortes; análise automática entra depois.',action:'Abrir Cortes',target:'#cutsStudio'},
image:{title:'🎨 Imagem & Design AI',text:'O Prompt Studio já prepara instruções visuais. O editor e geração dentro do ChatCreova estão sinalizados como Em construção.',action:'Abrir Prompt de Imagem',target:'#workspace'}};
$$('[data-guide]').forEach(b=>b.onclick=()=>{let f=flows[b.dataset.guide],box=$('#guideFlow');box.classList.remove('hidden');box.innerHTML=`<h3>${f.title}</h3><p>${f.text}</p><button class="primary" id="flowAction">${f.action} →</button>`;$('#flowAction').onclick=()=>show(f.target)});
const areaTargets={voice:'#voiceStudio',cuts:'#cutsStudio',music:'#musicStudio'};
$$('[data-area]').forEach(b=>b.onclick=()=>{let a=b.dataset.area;if(areaTargets[a])return show(areaTargets[a]);show('#workspace');selected=b.querySelector('b').textContent.replace(/^\S+\s/,'');$('#toolTitle').textContent=selected;$('#idea').focus()});
$$('[data-tool]').forEach(b=>b.onclick=()=>{selected=b.dataset.tool;$('#toolTitle').textContent=selected;$('#idea').focus()});
$$('.formats:not(.cuts) button').forEach(b=>b.onclick=()=>{$$('.formats:not(.cuts) button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
$('#generate').onclick=()=>{let idea=$('#idea').value.trim(),format=$('.formats:not(.cuts) .active').textContent,out=$('#result');out.classList.remove('hidden');if(!idea){out.textContent='Escreva uma ideia primeiro.';return}let extra=selected.includes('Roteiro')?'\n\nEstrutura sugerida:\n• Gancho\n• Desenvolvimento\n• Narração\n• Fechamento + CTA':selected.includes('Publicação')?'\n\nPacote sugerido:\n• Título\n• Descrição\n• CTA\n• Hashtags':selected.includes('Cenas')?'\n\nCenas sugeridas:\n1. Gancho visual\n2. Contexto\n3. Desenvolvimento\n4. Momento principal\n5. CTA':'\n\nO Prompt Studio acrescentará contexto, estilo, câmera, iluminação, movimento e consistência quando aplicável.';out.textContent=`BETA V4 — ${selected}\nFormato: ${format}\n\nSua ideia:\n${idea}${extra}\n\n✓ Demonstração local: 0 créditos reais consumidos.`};
$$('#cutsStudio .formats button').forEach(b=>b.onclick=()=>{$$('#cutsStudio .formats button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
$('#cutsBtn').onclick=()=>{let idea=$('#cutsIdea').value.trim(),sec=$('#cutsStudio .active').dataset.seconds,out=$('#cutsResult');out.classList.remove('hidden');if(!idea){out.textContent='Descreva primeiro o assunto do vídeo.';return}out.textContent=`PLANO DE CORTES — ${sec}s\n\nVídeo: ${idea}\n\n1. Gancho/pergunta forte\n2. Informação principal\n3. Exemplo/momento memorável\n4. Conclusão + CTA\n\nFormato recomendado: 9:16.`};
function voices(){return 'speechSynthesis'in window?speechSynthesis.getVoices():[]}
function likely(v,g){let n=(v.name||'').toLowerCase();let female=['female','feminina','mulher','maria','luciana','francisca','helena','leticia','victoria'];let male=['male','masculina','homem','daniel','antonio','felipe','ricardo'];return (g==='female'?female:male).some(x=>n.includes(x))}
function loadVoices(){let vs=voices(),sel=$('#voiceSelect');sel.innerHTML='';if(!vs.length){sel.innerHTML='<option value="">Voz padrão do aparelho</option>';return}let order=vs.map((v,i)=>({v,i})).sort((a,b)=>Number(likely(b.v,voiceGender))-Number(likely(a.v,voiceGender)));order.forEach(({v,i})=>{let o=document.createElement('option');o.value=i;o.textContent=`${likely(v,voiceGender)?'★ ':''}${v.name} — ${v.lang}`;sel.appendChild(o)})}
if('speechSynthesis'in window){loadVoices();speechSynthesis.onvoiceschanged=loadVoices}
$$('[data-gender]').forEach(b=>b.onclick=()=>{voiceGender=b.dataset.gender;$$('[data-gender]').forEach(x=>x.classList.toggle('active',x===b));loadVoices()});
$('#voiceText').oninput=()=>{let n=$('#voiceText').value.length;$('#charCount').textContent=`${n.toLocaleString('pt-BR')} / 7.000`;let words=$('#voiceText').value.trim()?$('#voiceText').value.trim().split(/\s+/).length:0;$('#duration').textContent=`≈ ${(words/145).toFixed(1).replace('.',',')} min`};
$('#speakBtn').onclick=()=>{if(!('speechSynthesis'in window))return alert('Seu navegador não oferece voz local.');let t=$('#voiceText').value.trim();if(!t)return alert('Digite ou cole uma narração primeiro.');speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t),vs=voices(),i=Number($('#voiceSelect').value);if(vs[i])u.voice=vs[i];u.lang=u.voice?.lang||'pt-BR';u.rate=Number($('#rate').value);u.pitch=Number($('#pitch').value);speechSynthesis.speak(u)};
$('#pauseBtn').onclick=()=>{if(!('speechSynthesis'in window))return;if(speechSynthesis.paused){speechSynthesis.resume();$('#pauseBtn').textContent='⏸ Pausar'}else{speechSynthesis.pause();$('#pauseBtn').textContent='▶ Continuar'}};
$('#stopBtn').onclick=()=>{if('speechSynthesis'in window)speechSynthesis.cancel();$('#pauseBtn').textContent='⏸ Pausar'};
$('#musicBtn').onclick=()=>{let n=$('#songName').value.trim()||'Projeto sem título',l=$('#lyrics').value.trim(),s=$('#musicStyle').value,o=$('#musicResult');o.classList.remove('hidden');o.textContent=`PROJETO MUSICAL — ${n}\nEstilo: ${s}\n\n${l?'Letra/ideia recebida e pronta para estruturar.':'Adicione uma letra ou ideia.'}\n\nIntro → Verso → Pré-refrão → Refrão → Verso → Refrão → Ponte → Refrão final.\n\nNenhum gerador pago conectado.`};
const help={start:'Use “Não sei por onde começar”. Escolha seu objetivo e siga o caminho sugerido.',credits:'Os 20 créditos são demonstração. Nenhum crédito real é comprado ou consumido nesta V4.',voice:'Abra Estúdio de Voz, cole até 7.000 caracteres, escolha feminina ou masculina, selecione a voz disponível e toque em Ouvir. As vozes variam conforme o aparelho.',create:'Escolha uma área ou use o Prompt Studio para preparar roteiro, cenas, publicação e outros materiais.',account:'Cadastro por Google/e-mail será conectado depois. A V4 não coleta senha nem dados bancários.',payments:'Nenhum pagamento está ativo. Só conectaremos cobrança quando os custos e a estrutura comercial estiverem definidos.'};
$$('[data-help]').forEach(b=>b.onclick=()=>{let o=$('#helpText');o.classList.remove('hidden');o.textContent=help[b.dataset.help]});