let selected='Criar Prompt Profissional';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function show(id){const e=$(id);e.classList.remove('hidden');e.scrollIntoView({behavior:'smooth',block:'start'})}
function hide(id){$(id).classList.add('hidden')}
$('#guideBtn').onclick=()=>show('#guide'); $('#fastBtn').onclick=()=>show('#workspace'); $('#helpBtn').onclick=()=>show('#help');
$$('[data-close]').forEach(b=>b.onclick=()=>hide('#'+b.dataset.close));
const flows={
 creator:{title:'🎬 Criadores & Redes',text:'Vamos fazer juntos: 1) escolha a rede social, 2) diga o tema, 3) escolha o formato, 4) o ChatCreova prepara roteiro, cenas, narração, CTA e publicação.',action:'Abrir Criadores & Redes',target:'#workspace'},
 sales:{title:'🛒 Vendas & E-commerce',text:'Comece pelo produto. Preserve sempre o produto original. Depois montamos gancho, anúncio, roteiro UGC, cenas, CTA, título, descrição e hashtags.',action:'Abrir fluxo de vendas',target:'#workspace'},
 education:{title:'🎓 Educação & Acadêmico',text:'Escolha: Aluno, Professor ou Universitário. O fluxo pode explicar matéria, montar estudo, atividade, aula, apresentação ou estrutura acadêmica.',action:'Abrir Educação',target:'#workspace'},
 voice:{title:'🎙️ Estúdio de Voz',text:'Cole seu texto, escolha uma voz disponível no aparelho e ouça a narração. Limite desta interface: 7.000 caracteres.',action:'Abrir Estúdio de Voz',target:'#voiceStudio'},
 cuts:{title:'✂️ Cortes Inteligentes',text:'Defina o assunto e a duração desejada. Nesta V3 criamos um plano de cortes. A leitura automática do vídeo será conectada depois.',action:'Abrir Cortes',target:'#cutsStudio'},
 image:{title:'🎨 Imagem & Design AI',text:'Diga a imagem desejada, escolha 9:16, 16:9 ou 1:1 e o Prompt Studio prepara uma instrução visual detalhada sem consumir API.',action:'Abrir Prompt de Imagem',target:'#workspace'}
};
$$('[data-guide]').forEach(b=>b.onclick=()=>{let f=flows[b.dataset.guide],box=$('#guideFlow');box.classList.remove('hidden');box.innerHTML=`<h3>${f.title}</h3><p>${f.text}</p><button class="primary" id="flowAction">${f.action} →</button>`;$('#flowAction').onclick=()=>show(f.target)});
const areaTargets={voice:'#voiceStudio',cuts:'#cutsStudio',music:'#musicStudio'};
$$('[data-area]').forEach(b=>b.onclick=()=>{let a=b.dataset.area;if(areaTargets[a])return show(areaTargets[a]);show('#workspace');selected=b.querySelector('b').textContent.replace(/^\S+\s/,'');$('#toolTitle').textContent=selected;$('#idea').focus()});
$$('[data-tool]').forEach(b=>b.onclick=()=>{selected=b.dataset.tool;$('#toolTitle').textContent=selected;$('#idea').focus()});
$$('.formats:not(.cuts) button').forEach(b=>b.onclick=()=>{$$('.formats:not(.cuts) button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
$('#generate').onclick=()=>{let idea=$('#idea').value.trim(),format=$('.formats:not(.cuts) .active').textContent,out=$('#result');out.classList.remove('hidden');if(!idea){out.textContent='Escreva uma ideia primeiro. O ChatCreova Guiado precisa saber o que você quer criar.';return}let extra=selected.includes('Roteiro')?'\n\nEstrutura sugerida:\n• Gancho nos primeiros segundos\n• Desenvolvimento em cenas curtas\n• Narração objetiva\n• Fechamento + CTA':selected.includes('Publicação')?'\n\nPacote sugerido:\n• Título forte\n• Descrição clara\n• CTA\n• Hashtags relacionadas':selected.includes('Cenas')?'\n\nCenas sugeridas:\n1. Gancho visual\n2. Contexto\n3. Desenvolvimento\n4. Momento principal\n5. Fechamento/CTA':'\n\nO Prompt Studio acrescentará contexto, estilo, câmera, iluminação, movimento e consistência quando aplicável.';out.textContent=`BETA V3 — ${selected}\nFormato: ${format}\n\nSua ideia:\n${idea}${extra}\n\n✓ Demonstração local: 0 créditos reais consumidos.`};
$$('#cutsStudio .formats button').forEach(b=>b.onclick=()=>{$$('#cutsStudio .formats button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
$('#cutsBtn').onclick=()=>{let idea=$('#cutsIdea').value.trim(),sec=$('#cutsStudio .active').dataset.seconds,out=$('#cutsResult');out.classList.remove('hidden');if(!idea){out.textContent='Descreva primeiro o assunto do vídeo.';return}out.textContent=`PLANO DE CORTES — ${sec}s\n\nVídeo: ${idea}\n\nCorte 1 — gancho/pergunta forte\nCorte 2 — informação ou virada principal\nCorte 3 — exemplo/reação/momento memorável\nCorte 4 — conclusão com CTA\n\nFormato recomendado: 9:16, legendas grandes e abertura direta.\n\nNesta V3 o plano é local; o vídeo ainda não é analisado automaticamente.`};
function loadVoices(){let vs=speechSynthesis.getVoices(),sel=$('#voiceSelect');sel.innerHTML='';if(!vs.length){sel.innerHTML='<option>Voz padrão do aparelho</option>';return}vs.forEach((v,i)=>{let o=document.createElement('option');o.value=i;o.textContent=`${v.name} — ${v.lang}`;sel.appendChild(o)})}if('speechSynthesis'in window){loadVoices();speechSynthesis.onvoiceschanged=loadVoices}
$('#voiceText').oninput=()=>{let n=$('#voiceText').value.length;$('#charCount').textContent=`${n.toLocaleString('pt-BR')} / 7.000`;$('#duration').textContent=`≈ ${Math.max(0,Math.round(n/850))} min`};
$('#speakBtn').onclick=()=>{if(!('speechSynthesis'in window))return alert('Seu navegador não oferece voz local.');let t=$('#voiceText').value.trim();if(!t)return alert('Digite ou cole uma narração primeiro.');speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t),vs=speechSynthesis.getVoices(),i=Number($('#voiceSelect').value);if(vs[i])u.voice=vs[i];u.lang=u.voice?.lang||'pt-BR';speechSynthesis.speak(u)};$('#stopBtn').onclick=()=>speechSynthesis?.cancel();
$('#musicBtn').onclick=()=>{let n=$('#songName').value.trim()||'Projeto sem título',l=$('#lyrics').value.trim(),s=$('#musicStyle').value,o=$('#musicResult');o.classList.remove('hidden');o.textContent=`PROJETO MUSICAL — ${n}\nEstilo: ${s}\n\n${l?'Letra/ideia recebida e pronta para estruturar.':'Adicione uma letra ou ideia para continuar.'}\n\nEstrutura sugerida: Intro → Verso → Pré-refrão → Refrão → Verso → Refrão → Ponte → Refrão final.\n\nNenhum gerador de música pago está conectado nesta V3.`};
const help={start:'Use “Não sei por onde começar”. Escolha seu objetivo e siga o caminho sugerido.',credits:'Os 20 créditos mostrados são apenas demonstração. Nenhum crédito real é comprado ou consumido nesta V3.',create:'Escolha uma área ou use o Prompt Studio. Você pode preparar roteiro, cenas, publicação e outros materiais.',account:'Cadastro por Google/e-mail será conectado em uma fase posterior. Nesta V3 não coletamos senha nem dados bancários.',payments:'Pix e cartão serão estudados antes da fase comercial. Nenhum pagamento está ativo agora.',support:'Durante o Beta, esta área será preparada para dúvidas, feedback e suporte. Nenhum atendimento externo está conectado ainda.'};
$$('[data-help]').forEach(b=>b.onclick=()=>{let o=$('#helpText');o.classList.remove('hidden');o.textContent=help[b.dataset.help]});
