const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const sidebar=$('#sidebar'), input=$('#mainInput'), chat=$('#chat');
const STORE='chatcreovaV12State', PROJECTS='chatcreovaV12Projects';
const ORDER=['home','manager','video','image','voice','music','prompts','sites','more','space'];
let currentView='home';
let state=JSON.parse(localStorage.getItem(STORE)||'null')||{brief:{},stage:0,lastRequest:'',deliveries:[],activeProject:false};
function persist(){localStorage.setItem(STORE,JSON.stringify(state))}
function toast(msg){let d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2600)}
function flowLabel(id){return ({home:'Início',manager:'Gerente',video:'Vídeo',image:'Imagem',voice:'Voz',music:'Música',prompts:'Prompts',sites:'Sites & Apps',more:'Mais ferramentas',space:'Meu Espaço'})[id]||id}
function updateFlow(){let i=ORDER.indexOf(currentView);$('#flowBack').disabled=i<=0;$('#flowContinue').disabled=i<0||i>=ORDER.length-1;$('#flowStatus').textContent=flowLabel(currentView)+' • '+(i+1)+' de '+ORDER.length;$('#flowContinue').textContent=i===ORDER.length-1?'Concluído ✓':'Continuar →'}
function openView(id){if(!document.getElementById(id))return toast('Área ainda não disponível.');currentView=id;$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));if(innerWidth<801)sidebar.classList.remove('open');updateFlow()}
$$('.nav').forEach(b=>b.onclick=()=>openView(b.dataset.view));$('#menuBtn').onclick=()=>sidebar.classList.toggle('open');
$('#flowBack').onclick=()=>{let i=ORDER.indexOf(currentView);if(i>0)openView(ORDER[i-1])};
$('#flowContinue').onclick=()=>{let i=ORDER.indexOf(currentView);if(i<ORDER.length-1)openView(ORDER[i+1]);else toast('Fluxo concluído.')};
$$('[data-open]').forEach(b=>b.onclick=()=>openView(b.dataset.open));
$$('[data-fill]').forEach(b=>b.onclick=()=>{input.value=b.dataset.fill;openView('manager');input.focus()});
$$('[data-manager]').forEach(b=>b.onclick=()=>{input.value=b.dataset.manager;openView('manager');input.focus()});
$$('.toolgrid article').forEach(card=>{if(card.querySelector('mark')?.textContent.includes('EM CONSTRUÇÃO')&&!card.dataset.manager&&!card.dataset.open){card.style.cursor='pointer';card.onclick=()=>toast('Em construção — nenhum crédito será cobrado.')}});
$('#loginBtn').onclick=()=>toast('Entrar: EM CONSTRUÇÃO — nenhum crédito será cobrado.');
function addMsg(kind,html){const d=document.createElement('div');d.className='msg '+kind;d.innerHTML=html;chat.appendChild(d);d.scrollIntoView({behavior:'smooth',block:'end'})}
function clean(s){return s.replace(/[<>]/g,'')}
function parseBrief(text){const t=text.toLowerCase(),b=state.brief;if(/facebook/.test(t))b.platform='Facebook';if(/instagram/.test(t))b.platform='Instagram';if(/tiktok/.test(t))b.platform='TikTok';if(/kwai/.test(t))b.platform='Kwai';let d=t.match(/(\d+)\s*(segundos?|s|minutos?|min)/);if(d)b.duration=d[1]+' '+(d[2].startsWith('m')?'minutos':'segundos');if(/salmo\s*91/.test(t))b.theme='Salmo 91';else if(/supera[cç][aã]o/.test(t))b.theme='história emocionante de superação';else {let m=text.match(/sobre\s+(.+?)(?:\.|,| para | com |$)/i);if(m)b.theme=m[1].trim()}if(/cinematogr/.test(t))b.style='cinematográfico';if(/produto|vender|e-commerce|ecommerce/.test(t))b.type='vendas';else if(/vídeo|video|reel|short/.test(t))b.type='vídeo';if(/imagem|foto|capa/.test(t)&&!b.type)b.type='imagem';if(/narra|voz|locu/.test(t)&&!b.type)b.type='voz';let sm=t.match(/\b(\d+)\s*cenas?/);if(sm)b.scenes=+sm[1];b.script=/roteiro/.test(t)||b.script;b.narration=/narra/.test(t)||b.narration;b.prompts=/prompts?/.test(t)||b.prompts;b.hashtags=/hashtags?/.test(t)||b.hashtags;b.description=/descri[cç][aã]o/.test(t)||b.description;b.cta=/\bcta\b/.test(t)||b.cta;persist();return b}
function teamFor(b){let a=['🧠 Gerente Geral'];if(b.type==='vídeo'||b.platform)a.push('✍️ Roteirista AI','🎬 Editor AI','📱 Social Media AI');if(b.narration||b.type==='voz')a.push('🎙️ Locutor AI');if(b.prompts||b.type==='imagem')a.push('🎨 Designer AI');if(b.type==='vendas')a.push('🛒 Vendas AI');return [...new Set(a)]}
function updateProgress(stage){let p=$('#progress');p.classList.remove('hidden');let spans=p.querySelectorAll('span');spans.forEach((s,i)=>{s.classList.remove('on','done','current');if(i<stage)s.classList.add('done');else if(i===Math.min(stage,spans.length-1))s.classList.add('current')})}
function delivery(b,stage){let theme=b.theme||'tema solicitado',platform=b.platform||'redes sociais',dur=b.duration||'60 segundos',n=b.scenes||8;if(stage===1)return `<b>🧠 Organização concluída</b><p><b>Projeto:</b> ${clean(theme)} • <b>Destino:</b> ${platform} • <b>Duração:</b> ${dur}</p><p>Contexto salvo. A produção vai continuar automaticamente.</p>`;if(stage===2){let scenes=Array.from({length:n},(_,i)=>`${i+1}. ${i===0?'Gancho visual forte':i===n-1?'Fechamento + CTA':'Progressão visual da história — cena '+(i+1)}`).join('<br>');return `<b>🎬 Produção</b><p><b>Roteiro-base:</b><br>“Toda mudança começa quando alguém decide continuar. ${clean(theme)} ganha força quando a história mostra dificuldade, decisão e transformação. Cada cena deve levar o público adiante, com emoção crescente e um fechamento claro. O próximo passo pode começar agora.”</p><p><b>${n} cenas:</b><br>${scenes}</p>`}if(stage===3)return `<b>🔎 Revisão</b><p><b>Direção visual:</b> realista, cinematográfica, emoção clara, continuidade entre cenas, sem texto embutido.</p><p><b>Prompt-base:</b> ${clean(theme)}, cena cinematográfica realista, iluminação dramática, composição adequada para ${platform}, alta definição, continuidade de personagem e ambiente.</p><p><b>Publicação:</b><br><b>Título:</b> Uma História Que Pode Mudar Seu Dia<br><b>Descrição:</b> Uma mensagem sobre ${clean(theme)} preparada para gerar atenção e reflexão.<br><b>CTA:</b> Comente o que mais falou com você e compartilhe.<br><b>Hashtags:</b> #Inspiração #História #Motivação #${platform.replace(/\s/g,'')}</p>`;return `<b>✅ Pronto</b><p>O pacote local foi concluído: organização, roteiro-base, cenas, direção visual, revisão e publicação. O que exigir geração externa continua desligado e não consumiu créditos.</p>`}
function runProject(text){parseBrief(text);state.lastRequest=text;state.activeProject=true;state.stage=1;persist();$('#team').classList.remove('hidden');$('#team').innerHTML='<b>Equipe selecionada:</b> '+teamFor(state.brief).join(' • ');let stages=[1,2,3,4];stages.forEach((st,i)=>setTimeout(()=>{state.stage=st;persist();updateProgress(st);addMsg('ai',delivery(state.brief,st))},250+i*500))}
function isContinue(t){return /^(sim|s|ok|pode|pode continuar|continua|continuar|vai|prossiga|segue|faça|faca)$/i.test(t.trim())||/pode continuar|continue|próxima etapa|proxima etapa/i.test(t)}
function send(){let text=input.value.trim();if(!text)return;openView('manager');addMsg('user',`<b>Você</b><p>${clean(text)}</p>`);input.value='';if(isContinue(text)&&state.activeProject){if(state.stage>=4)addMsg('ai','<b>🧠 Gerente Geral</b><p>Este projeto local já chegou a <b>Pronto</b>. Você pode pedir uma alteração ou iniciar outro projeto.</p>');else{for(let st=state.stage+1,i=0;st<=4;st++,i++)setTimeout(()=>{state.stage=st;persist();updateProgress(st);addMsg('ai',delivery(state.brief,st))},200+i*450)}return}runProject(text)}
$('#sendBtn').onclick=send;input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});
const filePicker=document.createElement('input');filePicker.type='file';filePicker.hidden=true;filePicker.multiple=true;document.body.appendChild(filePicker);$('#attachBtn').onclick=()=>filePicker.click();filePicker.onchange=()=>{let files=[...filePicker.files];if(!files.length)return;openView('manager');addMsg('ai',`<b>📎 Anexo local</b><p>${files.map(f=>clean(f.name)+' — '+Math.ceil(f.size/1024)+' KB').join('<br>')}</p><p>Selecionado localmente. Nenhuma API paga foi usada.</p>`)};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;$('#micBtn').onclick=()=>{if(!SR)return toast('Reconhecimento de fala não está disponível neste navegador.');let r=new SR();r.lang='pt-BR';r.onresult=e=>{input.value=e.results[0][0].transcript;input.focus()};r.start()};
$('#helpBtn').onclick=()=>$('#helpModal').classList.remove('hidden');$('#closeHelp').onclick=()=>$('#helpModal').classList.add('hidden');
const vt=$('#voiceText'),vc=$('#voiceSelect');function voices(){let vs=speechSynthesis.getVoices();vc.innerHTML=vs.map((v,i)=>`<option value="${i}">${v.name} — ${v.lang}</option>`).join('')}voices();speechSynthesis.onvoiceschanged=voices;vt.oninput=()=>{$('#count').textContent=vt.value.length;$('#duration').textContent='~'+Math.max(0,Math.round(vt.value.trim().split(/\s+/).filter(Boolean).length/150))+' min'};$('#speak').onclick=()=>{speechSynthesis.cancel();if(!vt.value.trim())return toast('Digite ou cole uma narração primeiro.');let u=new SpeechSynthesisUtterance(vt.value),vs=speechSynthesis.getVoices();if(vs[+vc.value])u.voice=vs[+vc.value];u.lang=u.voice?.lang||'pt-BR';speechSynthesis.speak(u)};$('#pause').onclick=()=>speechSynthesis.paused?speechSynthesis.resume():speechSynthesis.pause();$('#stop').onclick=()=>speechSynthesis.cancel();
function renderProjects(){let a=JSON.parse(localStorage.getItem(PROJECTS)||'[]');$('#savedProjects').innerHTML=a.map(x=>`<article class="msg ai"><b>${clean(x.name)}</b><p>${clean(x.notes)}</p></article>`).join('')}$('#saveProject').onclick=()=>{let name=$('#projectName').value.trim(),notes=$('#projectNotes').value.trim();if(!name)return toast('Digite o nome do projeto.');let a=JSON.parse(localStorage.getItem(PROJECTS)||'[]');a.unshift({name,notes});localStorage.setItem(PROJECTS,JSON.stringify(a.slice(0,30)));renderProjects();toast('Projeto salvo neste navegador.')};renderProjects();updateFlow();
