const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const input=$('#mainInput'),chat=$('#chat'),sidebar=$('#sidebar');
const STORE='chatcreovaV14State',PROJECTS='chatcreovaV14Projects';
let currentView='home';
let state=JSON.parse(localStorage.getItem(STORE)||'null')||{activeProjectId:null,projects:{}};
const persist=()=>localStorage.setItem(STORE,JSON.stringify(state));
const clean=s=>String(s??'').replace(/[<>]/g,'');
const id=(p='id')=>p+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
function openView(view,source='manual'){if(source!=='manual')throw new Error('V14: navegação interna bloqueada');if(!document.getElementById(view))return;currentView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(innerWidth<801)sidebar.classList.remove('open')}
$$('.nav').forEach(b=>b.onclick=()=>openView(b.dataset.view,'manual'));$$('[data-open]').forEach(b=>b.onclick=()=>openView(b.dataset.open,'manual'));
$$('[data-manager]').forEach(b=>b.onclick=()=>{input.value=b.dataset.manager;openView('manager','manual');input.focus()});
$('#menuBtn').onclick=()=>sidebar.classList.toggle('open');
function addMsg(kind,html){let d=document.createElement('div');d.className='msg '+kind;d.innerHTML=html;chat.appendChild(d);d.scrollIntoView({behavior:'smooth',block:'end'})}
function active(){return state.projects[state.activeProjectId]||null}
function requestedOutput(text){let t=text.toLowerCase();if(/\b(crie|faça|faca|gere|quero)\b.{0,35}\b(imagem|foto|capa|thumbnail|arte)\b/.test(t))return'image';if(/\b(crie|faça|faca|monte|quero)\b.{0,35}\b(vídeo|video|reel|short)\b/.test(t))return'video';if(/\b(roteiro|script)\b/.test(t))return'script';if(/\b(narração|narracao|locução|locucao)\b/.test(t)&&!/\bvídeo|video\b/.test(t))return'narration';if(/\b(currículo|curriculo|e-mail|email|relatório|relatorio|documento|carta)\b/.test(t))return'document';if(/\b(letra|música|musica|canção|cancao)\b/.test(t))return'music';if(/\bprompt\b/.test(t))return'prompt';return null}
function domainFor(output,text){if(output==='image')return'image';if(output==='video'||output==='script'||output==='narration')return'video';if(output==='document')return'office';if(output==='music')return'music';if(output==='prompt')return'prompt';let t=text.toLowerCase();if(/shopee|produto|vender|e-commerce|anúncio|anuncio/.test(t))return'sales';if(/escola|aluno|professor|universit|acadêmic/.test(t))return'education';return'general'}
function classify(text){let p=active();if(/^(sim|ok|pode|continua|continuar|vai|prossiga)$/i.test(text.trim())&&p)return{kind:'CONTINUAR',output:p.output,domain:p.domain};if(/^(mude|muda|troque|troca|altere|ajuste|corrija)/i.test(text.trim())&&p){let o=requestedOutput(text)||p.output;return{kind:'MODIFICAR',output:o,domain:domainFor(o,text)}}let o=requestedOutput(text);return{kind:'NOVO_PROJETO',output:o,domain:domainFor(o,text)}}
function brief(text){let b={request:text};let m=text.match(/\b(\d+)\s*cenas?/i);if(m)b.scenes=+m[1];let d=text.match(/\b(\d+)\s*(segundos?|minutos?|min|s)\b/i);if(d)b.duration=d[1]+' '+d[2];if(/16[:x]9/i.test(text))b.format='16:9';else if(/1[:x]1/i.test(text))b.format='1:1';else b.format='9:16';let s=text.match(/sobre\s+(.+?)(?:,|\.| com | para |$)/i);b.theme=s?s[1].trim():text.replace(/^(crie|faça|faca|gere|monte)\s+(um|uma)?\s*(vídeo|video|imagem|roteiro|script)?\s*/i,'').trim();return b}
function newProject(text,r){let p={id:id('proj'),domain:r.domain,output:r.output,status:'PEDIDO',brief:brief(text),tasks:[],artifacts:{},qa:{approved:false,errors:[]},history:[text],createdAt:Date.now()};state.projects[p.id]=p;state.activeProjectId=p.id;persist();return p}
const teams={video:['✍️ Roteirista','🎨 Diretor Visual','🎙️ Narrador','📱 Social Media'],image:['🎨 Diretor Visual','🧬 Continuidade Visual'],office:['💼 Assistente Profissional','✍️ Redator'],music:['🎵 Compositor','✍️ Letrista'],prompt:['✨ Engenheiro de Prompts'],sales:['🛒 Estrategista de Vendas','✍️ Copywriter'],education:['🎓 Assistente Acadêmico','✍️ Redator Didático'],general:['🧠 Assistente Geral']};
function createArtifact(type,content,worker){if(!content)return null;return{id:id('art'),type,content,createdBy:worker,createdAt:Date.now(),status:'CREATED'}}
function makeScript(p){let th=clean(p.brief.theme);return `GANCHO: ${th} começa com uma pergunta ou situação capaz de prender a atenção imediatamente.\n\nDESENVOLVIMENTO: Apresente o contexto, aumente a tensão e conduza a história em progressão clara, sem repetir informações. Mostre o conflito principal, a decisão central e suas consequências.\n\nCLÍMAX: Entregue o momento de maior impacto de ${th}, deixando evidente a transformação ou mensagem principal.\n\nFECHAMENTO: Retome a ideia central com uma conclusão objetiva e memorável.`}
function makeVideo(p){let n=p.brief.scenes||8,script=makeScript(p),th=clean(p.brief.theme),fmt=p.brief.format;let scenes=Array.from({length:n},(_,i)=>({num:i+1,prompt:`Cena ${i+1}/${n} — ${th}. Ação específica correspondente à progressão ${i+1} da narrativa; personagem consistente, cenário coerente, expressão clara, composição cinematográfica, iluminação realista, profundidade natural, sem texto, ${fmt}.`,motion:`Movimento de câmera natural na cena ${i+1}; preservar personagem, anatomia, figurino e cenário.`}));return{script,scenes,title:`${th} — história completa`,description:`Vídeo sobre ${th} com narrativa, cenas e direção visual integradas.`,cta:'Comente o que mais marcou você e compartilhe.',hashtags:'#ChatCreova #Video #Criacao'}}
function executeWorkers(p){p.tasks=[];let workers=teams[p.domain]||teams.general;let artifacts=[];
if(p.output==='video'){let v=makeVideo(p);artifacts.push(createArtifact('video_project',v,workers[0]));}
else if(p.output==='script'){artifacts.push(createArtifact('script',makeScript(p),workers[0]));}
else if(p.output==='narration'){artifacts.push(createArtifact('narration',makeScript(p),workers[0]));}
else if(p.output==='prompt'){artifacts.push(createArtifact('prompt',`Objetivo: ${clean(p.brief.theme)}\nFormato: saída completa e específica.\nRegras: sem placeholders; preservar restrições e referências fornecidas; informar claramente o resultado esperado.`,workers[0]));}
else if(p.output==='document'){artifacts.push(createArtifact('document',`DOCUMENTO PROFISSIONAL\n\nObjetivo: ${clean(p.brief.theme)}\n\nConteúdo-base organizado para revisão e preenchimento dos dados específicos fornecidos pelo usuário.`,workers[0]));}
else if(p.output==='music'){artifacts.push(createArtifact('music_plan',`TEMA: ${clean(p.brief.theme)}\nESTRUTURA: Intro → Verso 1 → Pré-refrão → Refrão → Verso 2 → Ponte → Refrão final.\nDIREÇÃO: letra original, refrão memorável e coerência de estilo.`,workers[0]));}
else if(p.output==='image'){p.status='BLOQUEADO_PROVIDER';return{artifacts:[],blocked:'A geração de imagem real está desligada nesta versão local. O Gerente não vai fingir que criou uma imagem.'}}
else return{artifacts:[],needsClarification:true};
for(let i=0;i<workers.length;i++){let a=artifacts[i]||artifacts[0];p.tasks.push({id:id('task'),worker:workers[i],status:a?'SUCCESS':'PENDING',artifactId:a?.id||null})}
artifacts.forEach(a=>p.artifacts[a.id]=a);return{artifacts}}
function qa(p,result){let e=[];if(!result.artifacts?.length)e.push('nenhum artefato válido produzido');for(let a of result.artifacts||[]){if(!a.content)e.push('artefato vazio');if(JSON.stringify(a.content).match(/placeholder|lorem ipsum/i))e.push('placeholder detectado');if(a.type==='video_project'){let n=p.brief.scenes||8;if(a.content.scenes?.length!==n)e.push(`quantidade de cenas incorreta: esperado ${n}`);if(!a.content.script||!a.content.title||!a.content.description||!a.content.cta)e.push('pacote de vídeo incompleto')}}p.qa={approved:e.length===0,errors:e};return p.qa}
function progress(stage){let box=$('#progress');box.classList.remove('hidden');box.querySelectorAll('span').forEach((s,i)=>{s.className=i<stage?'done':i===stage?'current':''})}
function renderArtifact(a){if(a.type==='video_project'){let v=a.content;return `<p><b>Título:</b> ${clean(v.title)}</p><p><b>Roteiro:</b><br>${clean(v.script).replace(/\n/g,'<br>')}</p>${v.scenes.map(s=>`<p><b>Cena ${s.num}</b><br><b>Prompt:</b> ${clean(s.prompt)}<br><b>Movimento:</b> ${clean(s.motion)}</p>`).join('')}<p><b>Descrição:</b> ${clean(v.description)}<br><b>CTA:</b> ${clean(v.cta)}<br><b>Hashtags:</b> ${clean(v.hashtags)}</p>`}return `<p>${clean(a.content).replace(/\n/g,'<br>')}</p>`}
function run(p,intent){let startView=currentView;$('#team').classList.remove('hidden');$('#team').innerHTML=`<b>${intent} • ${clean(p.domain.toUpperCase())}</b><br>Equipe interna: ${(teams[p.domain]||teams.general).join(' • ')}<br><small>A interface permanecerá em ${clean(startView)}.</small>`;progress(1);p.status='ORGANIZAÇÃO';addMsg('ai',`<b>🧠 Gerente Geral</b><p>Pedido organizado. Vou delegar tarefas internamente sem mudar sua tela.</p>`);setTimeout(()=>{progress(2);p.status='PRODUÇÃO';let result=executeWorkers(p);persist();if(result.needsClarification){p.status='AGUARDANDO';addMsg('ai','<b>🧠 Gerente Geral</b><p>O tema foi entendido, mas falta o tipo de entrega. Você quer imagem, vídeo, roteiro, narração, documento, música ou prompt?</p>');return}if(result.blocked){progress(3);p.qa={approved:false,errors:[result.blocked]};addMsg('ai',`<b>🛡️ QA • NÃO APROVADO</b><p>${clean(result.blocked)}</p><p>Status: não está PRONTO.</p>`);persist();return}let q=qa(p,result);progress(3);if(!q.approved){p.status='CORREÇÃO';addMsg('ai',`<b>🛡️ QA • CORREÇÃO</b><p>${q.errors.map(clean).join('<br>')}</p>`);persist();return}p.status='PRONTO';progress(4);let arts=Object.values(p.artifacts);addMsg('ai',`<b>📦 Entrega do Gerente</b>${arts.map(renderArtifact).join('')}<p><b>✅ PRONTO</b> — QA aprovou artefato real.</p>`);persist();saveProject(p)},350)}
function send(){let text=input.value.trim();if(!text)return;let visible=currentView;if(visible!=='manager'){addMsg('user',`<b>Você</b><p>${clean(text)}</p>`)}else addMsg('user',`<b>Você</b><p>${clean(text)}</p>`);input.value='';let r=classify(text),p=active();if(r.kind==='NOVO_PROJETO')p=newProject(text,r);else if(!p)p=newProject(text,r);else{p.history.push(text);if(r.kind==='MODIFICAR'){p.output=r.output;p.domain=r.domain;p.brief=brief(text);p.status='PEDIDO';p.artifacts={};p.qa={approved:false,errors:[]}}persist()}run(p,r.kind)}
$('#sendBtn').onclick=send;input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});
function saveProject(p){let a=JSON.parse(localStorage.getItem(PROJECTS)||'[]');a=[{id:p.id,name:(p.brief.theme||p.domain).slice(0,80),status:p.status},...a.filter(x=>x.id!==p.id)].slice(0,30);localStorage.setItem(PROJECTS,JSON.stringify(a));renderProjects()}
function renderProjects(){let a=JSON.parse(localStorage.getItem(PROJECTS)||'[]');$('#savedProjects').innerHTML=a.map(x=>`<div class="msg ai"><b>${clean(x.name)}</b><p>${clean(x.status)} • ${clean(x.id)}</p></div>`).join('')}
const filePicker=document.createElement('input');filePicker.type='file';filePicker.multiple=true;filePicker.hidden=true;document.body.appendChild(filePicker);$('#attachBtn').onclick=()=>filePicker.click();
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;$('#micBtn').onclick=()=>{if(!SR)return;let r=new SR();r.lang='pt-BR';r.onresult=e=>input.value=e.results[0][0].transcript;r.start()};
$('#helpBtn').onclick=()=>$('#helpModal').classList.remove('hidden');$('#closeHelp').onclick=()=>$('#helpModal').classList.add('hidden');
const vt=$('#voiceText'),vc=$('#voiceSelect');function voices(){let vs=speechSynthesis.getVoices();vc.innerHTML=vs.map((v,i)=>`<option value="${i}">${v.name} — ${v.lang}</option>`).join('')}voices();speechSynthesis.onvoiceschanged=voices;vt.oninput=()=>{$('#count').textContent=vt.value.length;$('#duration').textContent='~'+Math.round(vt.value.trim().split(/\s+/).filter(Boolean).length/150)+' min'};$('#speak').onclick=()=>{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(vt.value),vs=speechSynthesis.getVoices();if(vs[+vc.value])u.voice=vs[+vc.value];speechSynthesis.speak(u)};$('#pause').onclick=()=>speechSynthesis.paused?speechSynthesis.resume():speechSynthesis.pause();$('#stop').onclick=()=>speechSynthesis.cancel();
renderProjects();
