const MODEL="qwen3.5:4b",API="http://localhost:11434/api/chat";let history=[],channels=JSON.parse(localStorage.getItem("chatcreova_channels_v15")||"[]");const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function view(id){$$(".view").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active")}$$("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));$$("[data-fill]").forEach(b=>b.onclick=()=>{view("chat");$("#input").value=b.dataset.fill;$("#input").focus()});
function esc(s=""){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function render(){let s=$("#channelSelect");s.innerHTML='<option value="">Sem canal/marca selecionado</option>';channels.forEach((c,i)=>s.insertAdjacentHTML("beforeend",`<option value="${i}">${esc(c.name)}</option>`));$("#channelCards").innerHTML=channels.map((c,i)=>`<div class="card"><b>${esc(c.name)}</b><p>${esc(c.platform)} ${c.niche?"• "+esc(c.niche):""}</p><small>${esc(c.rules)}</small><br><button onclick="useCh(${i})">Usar no chat</button> <button onclick="delCh(${i})">Excluir</button></div>`).join("")}
$("#saveChannel").onclick=()=>{let c={name:$("#chName").value.trim(),platform:$("#chPlatform").value.trim(),niche:$("#chNiche").value.trim(),language:$("#chLanguage").value.trim(),rules:$("#chRules").value.trim()};if(!c.name)return alert("Digite o nome.");channels.push(c);localStorage.setItem("chatcreova_channels_v15",JSON.stringify(channels));render()};window.useCh=i=>{view("chat");$("#channelSelect").value=i};window.delCh=i=>{channels.splice(i,1);localStorage.setItem("chatcreova_channels_v15",JSON.stringify(channels));render()};
function sys(support=false){let p=`Você é a IA do ChatCreova AI. Responda em português do Brasil natural e correto, salvo pedido diferente. Entregue conteúdo real e completo. Nunca finja execução. Nunca marque algo como pronto se faltarem partes. Respeite exatamente duração, quantidade de cenas e campos pedidos. Para roteiros, use boa continuidade, narração natural e prompts visuais detalhados. Revise a gramática antes de responder. Não exponha raciocínio interno; mostre somente a resposta útil.`;if(support)p+="\nModo Suporte ChatCreova: explique em passos curtos e não invente funções.";let i=$("#channelSelect").value;if(i!==""){let c=channels[+i];p+=`\nCANAL/MARCA: ${c.name}\nPlataforma: ${c.platform}\nNicho: ${c.niche}\nIdioma: ${c.language}\nRegras: ${c.rules}\nNão misture com outros projetos.`}return p}
async function ai(text,support=false){let messages=[{role:"system",content:sys(support)},...(support?[]:history),{role:"user",content:text}];let r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,messages,stream:false,think:false})});if(!r.ok)throw Error("Ollama respondeu "+r.status);let d=await r.json();return d.message?.content||"Resposta vazia."}
function msg(role,text){let d=document.createElement("div");d.className="msg "+(role==="user"?"user":"ai");d.textContent=text;$("#messages").appendChild(d);$("#messages").scrollTop=$("#messages").scrollHeight;return d}
async function send(){let t=$("#input").value.trim();if(!t)return;$("#input").value="";msg("user",t);let out=msg("ai","Pensando...");$("#send").disabled=true;try{let a=await ai(t);out.textContent=a;history.push({role:"user",content:t},{role:"assistant",content:a});if(history.length>20)history=history.slice(-20)}catch(e){out.textContent="IA local não conectada. Confirme que o Ollama está aberto. "+e.message}$("#send").disabled=false}
$("#send").onclick=send;$("#input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}};$("#helpBtn").onclick=()=>$("#help").classList.add("on");$("#closeHelp").onclick=()=>$("#help").classList.remove("on");$("#helpSend").onclick=async()=>{let q=$("#helpInput").value.trim();if(!q)return;$("#helpAnswer").textContent="Consultando...";try{$("#helpAnswer").textContent=await ai(q,true)}catch(e){$("#helpAnswer").textContent="IA local não conectada."}};
async function health(){try{let r=await fetch("http://localhost:11434/api/tags");let d=await r.json();let ok=(d.models||[]).some(m=>m.name===MODEL);$("#status").textContent=ok?"● Qwen conectado":"● Ollama ativo • Qwen não encontrado";$("#status").className=ok?"ok":"bad"}catch(e){$("#status").textContent="● IA local não conectada";$("#status").className="bad"}}render();health();