(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const input=$("#input"),messages=$("#messages"),help=$("#help"),send=$("#send"),status=$("#aiStatus");
const KEY="chatcreova_v17_channels",OLLAMA="http://127.0.0.1:11434",MODEL="qwen3.5:4b";
const history=[{role:"system",content:"Você é o ChatCreova AI, assistente oficial da plataforma ChatCreova. Responda em português do Brasil por padrão, salvo pedido em outro idioma. Converse naturalmente, execute o pedido e entregue conteúdo completo, sem placeholders. Não exponha raciocínio interno. Se perguntarem pelo motor, explique com transparência que neste teste local o ChatCreova usa Qwen pelo Ollama."}];
function st(t,s=""){if(status){status.textContent=t;status.dataset.state=s}}
function view(id){$$(".view").forEach(v=>v.classList.toggle("active",v.id===id))}
function fill(t){view("chat");input.value=t;input.focus()}
function msg(role,text){const d=document.createElement("div");d.className="msg "+role;const b=document.createElement("b");b.textContent=role==="user"?"Você":"✦ ChatCreova AI";const p=document.createElement("p");p.textContent=text;d.append(b,p);messages.append(d);messages.scrollTop=messages.scrollHeight;return p}
function get(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}
function set(x){localStorage.setItem(KEY,JSON.stringify(x))}
function render(){const a=get(),s=$("#channelSelect"),cards=$("#channelCards");s.innerHTML='<option value="">Sem canal/marca selecionado</option>';cards.innerHTML="";a.forEach((c,i)=>{const o=document.createElement("option");o.value=i;o.textContent=c.name;s.append(o);const d=document.createElement("div");d.className="panel";d.textContent=c.name+" — "+[c.platform,c.niche,c.language].filter(Boolean).join(" • ");cards.append(d)})}
function ctx(){const s=$("#channelSelect");if(!s||s.value==="")return"";const c=get()[Number(s.value)];if(!c)return"";return `\n\nContexto do canal/marca:\nNome: ${c.name||""}\nPlataforma: ${c.platform||""}\nNicho: ${c.niche||""}\nIdioma: ${c.language||""}\nRegras: ${c.rules||""}`}
function openHelp(){help.classList.add("open")} function closeHelp(){help.classList.remove("open")}
async function timed(url,opt={},ms=180000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(timer)}}
async function chat(m){const r=await timed(OLLAMA+"/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model:MODEL,messages:m,stream:false,think:false,keep_alive:"10m"})});if(!r.ok)throw Error("HTTP "+r.status);const d=await r.json();let x=d?.message?.content?.trim()||"";x=x.replace(/<think>[\s\S]*?<\/think>/gi,"").trim();if(!x)throw Error("Resposta vazia");return x}
async function check(){st("● Verificando IA local...","checking");try{const r=await timed(OLLAMA+"/api/tags",{cache:"no-store"},10000);if(!r.ok)throw Error("HTTP "+r.status);const d=await r.json();const ok=Array.isArray(d.models)&&d.models.some(m=>m.name===MODEL||m.model===MODEL);st(ok?"● IA local conectada":"● Qwen não encontrado",ok?"connected":"error");return ok}catch(e){console.error(e);st("● IA local bloqueada","error");return false}}
function err(e){if(e?.name==="AbortError")return"A IA local demorou demais para responder.";if(e instanceof TypeError)return"O navegador não conseguiu acessar o Ollama local. A página foi bloqueada ao tentar falar com 127.0.0.1:11434.";return"Falha na IA local: "+(e?.message||"erro desconhecido.")}
async function sendMsg(){const t=input.value.trim();if(!t||send.disabled)return;msg("user",t);input.value="";const w=msg("ai","Pensando...");history.push({role:"user",content:t+ctx()});send.disabled=true;input.disabled=true;try{const a=await chat(history);w.textContent=a;history.push({role:"assistant",content:a});st("● IA local conectada","connected")}catch(e){console.error(e);w.textContent=err(e);history.pop();st("● IA local bloqueada","error")}finally{send.disabled=false;input.disabled=false;input.focus()}}
$$("[data-view]").forEach(b=>b.onclick=()=>view(b.dataset.view));$$("[data-fill]").forEach(b=>b.onclick=()=>fill(b.dataset.fill));send.onclick=sendMsg;input.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMsg()}};
$("#saveChannel").onclick=()=>{const n=$("#chName").value.trim();if(!n)return alert("Digite o nome do canal ou marca.");const a=get();a.push({name:n,platform:$("#chPlatform").value.trim(),niche:$("#chNiche").value.trim(),language:$("#chLanguage").value.trim(),rules:$("#chRules").value.trim()});set(a);render()};
$("#helpBtn").onclick=openHelp;$("#helpSideBtn").onclick=openHelp;$("#closeHelp").onclick=closeHelp;
$("#helpSend").onclick=async()=>{const q=$("#helpInput").value.trim(),a=$("#helpAnswer");if(!q){a.textContent="Digite sua dúvida sobre o ChatCreova.";return}a.textContent="Pensando...";try{a.textContent=await chat([{role:"system",content:"Você é o Suporte IA do ChatCreova. Responda em português do Brasil, de forma simples e passo a passo. Não invente funções."},{role:"user",content:q}])}catch(e){a.textContent=err(e)}};
help.onclick=e=>{if(e.target===help)closeHelp()};render();view("chat");check();
})();